spring.application.name=DepartmentService

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=muthu
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA schema mapping
spring.jpa.properties.hibernate.default_schema=department
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9090